server:
  port: 9411
spring:
  application:
      name: zipkin-server
zipkin:
  collector:
    rabbitmq:
      addresses: localhost:5672
      password: guest
      username: guest
      queue: zipkin
  storage:
    type: elasticsearch
    StorageComponent: elasticsearch
    elasticsearch:
      cluster: elasticsearch
      max-requests: 30
      index: user
      index-shards: 3
      index-replicas: 1
      hosts: localhost:9200
#  storage:
#    type: elasticsearch
#    elasticsearch:
#      cluster: elasticsearch
#      hosts: http://localhost:9200
#      index: zipkin
#      index-shards: 5
#      index-replicas: 1

#zipkin:
#  storage:
#    type: elasticsearch
#    StorageComponent: elasticsearch
#    elasticsearch:
#      cluster: elasticsearch
#      max-requests: 30
#      index: zipkin
#      index-shards: 3
#      index-replicas: 1
#      hosts: localhost:9200


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true