/*用户简表*/
CREATE TABLE USR(
USRID VARCHAR(80) NOT NULL,
PWD VARCHAR(80) NOT NULL,
IDENTITY VARCHAR(50) NOT NULL,
IDSTATUS VARCHAR(50) NOT NULL DEFAULT "NORMAL",
CONSTRAINT PRIMARY KEY (USRID)
);

/*创建管理员*/
INSERT INTO USR(USRID,PWD,IDENTITY)
VALUES('管理员','guanliyuan','administrator');


/*学生详尽信息表*/
CREATE TABLE Student(
STUID VARCHAR(80) NOT NULL,
STUCLASS VARCHAR(50) NOT NULL,
STUNAME VARCHAR(50) NOT NULL,
STUMAIL VARCHAR(100) NOT NULL,
STUSCHOOL VARCHAR(50) NOT NULL,
STUTELPHONE VARCHAR(50) NOT NULL,
STUMAJOR VARCHAR(50) NOT NULL,
CONSTRAINT STU_USR_FX FOREIGN KEY(STUID) REFERENCES USR(USRID)
);

/*教师详尽信息表*/
CREATE TABLE TEACHER(
TEAID VARCHAR(80) NOT NULL,
TEANAME VARCHAR(50) NOT NULL,
TEAMAIL VARCHAR(100) NOT NULL,
TEATELPHONEL VARCHAR(50) NOT NULL,
CONSTRAINT TEA_USR_FX FOREIGN KEY(TEAID) REFERENCES USR(USRID)
);


/*问卷表*/
CREATE TABLE QUESTIONNAIRE(
WID INT AUTO_INCREMENT,
SUBJECT VARCHAR(100) NOT NULL,
STEMNUM INT NOT NULL,
TEAID VARCHAR(80) NOT NULL,
CREATETIME DATETIME NOT NULL,
CONSTRAINT QU_TEA_FX FOREIGN KEY(TEAID) REFERENCES USR(USRID),
PRIMARY KEY(WID),
UNIQUE KEY(TEAID,SUBJECT)
);

/*选题表*/
CREATE TABLE SELECTQUESTION(
WID INT AUTO_INCREMENT,
TIDNO INT NOT NULL,
TID INT NOT NULL,
PRIMARY KEY(WID,TIDNO),
CONSTRAINT SQ_QUONNAIE_FX FOREIGN KEY(WID) REFERENCES QUESTIONNAIRE(WID)
);


/*题目表*/
CREATE TABLE QUESTION(
TID INT AUTO_INCREMENT,
STEM VARCHAR(200) NOT NULL,
OPTIONNUM INT NOT NULL,
TYPE VARCHAR(50) NOT NULL,
TEAID VARCHAR(80) NOT NULL,
PRIMARY KEY(TID)
);


/*选项表*/
CREATE TABLE MYOPTION(
TID INT NOT NULL,
OPTIONID INT NOT NULL,
ANSWERID INT DEFAULT 0,
PRIMARY KEY(TID,OPTIONID),
CONSTRAINT OP_QUON_FX FOREIGN KEY(TID) REFERENCES QUESTION(TID)
); 

/*答案表*/
CREATE TABLE ANSWER(
ANSWERID INT AUTO_INCREMENT,
CONTENT VARCHAR(200),
TEAID VARCHAR(80) NOT NULL,
PRIMARY KEY(ANSWERID),
UNIQUE KEY(CONTENT,TEAID)
);

/*样本表*/
CREATE TABLE SYMBOL(
FEATURE VARCHAR(50) NOT NULL,
TEAID  VARCHAR(80) NOT NULL,
PRIMARY KEY(FEATURE,TEAID)
);

/*调查表*/
CREATE TABLE SURVEY(
WID INT NOT NULL,
ACTIVITY VARCHAR(100) NOT NULL,
STARTTIME DATETIME NOT NULL,
ENDTIME DATETIME NOT NULL,
MYGROUP VARCHAR(50) NOT NULL,
TEAID VARCHAR(80) NOT NULL
);

/*约束表*/
CREATE TABLE MYRESTRICT(
WID INT NOT NULL,
crisisTID INT NOT NULL,
crisisPID INT NOT NULL,
startTID INT NOT NULL,
endTID INT NOT NULL,
PRIMARY KEY(WID,crisisTID,crisisPID)
);

/*答案回收表*/
CREATE TABLE collectAnswer(
WID INT NOT NULL,
TIDNO INT NOT NULL,
ANSWERID VARCHAR(200) NOT NULL,
STUID VARCHAR(80) NOT NULL,
ANSWERTIME DATETIME NOT NULL,
TEAID  VARCHAR(80) NOT NULL,
ACTIVITY VARCHAR(100) NOT NULL
);

/*日志表*/
CREATE TABLE LOG(
usrName VARCHAR(80) NOT NULL,
time DATETIME NOT NULL,
ipAddress VARCHAR(50),
operation VARCHAR(80) NOT NULL
);





/*查询*/
SELECT * FROM USR;
SELECT * FROM Student;
SELECT * FROM TEACHER;
SELECT * FROM QUESTIONNAIRE;
SELECT * FROM SELECTQUESTION;
SELECT * FROM QUESTION;
SELECT * FROM MYOPTION;
SELECT * FROM ANSWER;
SELECT * FROM SYMBOL;
SELECT * FROM SURVEY;
SELECT * FROM MYRESTRICT;
SELECT * FROM collectAnswer;
SELECT * FROM log;



DELETE FROM collectAnswer WHERE WID='20' 
AND STUID='B13040333' AND ACTIVITY='我的测试活动'



DELETE FROME collectAnswer WHEREWID='20' 
AND STUID='B13040333' AND ACTIVITY='我的测试活动'

SELECT * FROM collectAnswer WHERE WID='19' AND STUID='B13040333'
SELECT * FROM QUESTION WHERE TID='1'
INSERT INTO collectAnswer(WID,TID,ANSWERID,STUID,ANSWERTIME,TEAID,ACTIVITY)
VALUES('20','5','纳西喜爱','B13040333',NOW(),'T130401','对李老师的评价')
INSERT INTO MYOPTION(TID,optionID,answerID)VALUES('1','1','2')

INSERT INTO QUESTION(TID,STEM,OPTIONNUM,TYPE)VALUES('1','你好吗','1','danxuan')
INSERT INTO MYOPTION(TID,optionID,answerID)VALUES('1','1','1')

SELECT * FROM log WHERE TIME<'2015-3-10 12：00';

SELECT * FROM log WHERE TIME LIKE '%2016%';

SELECT * FROM QUESTIONNAIRE 
WHERE TEAID='T130401' AND subject='我的测试' AND stemNum='2'

INSERT INTO QUESTIONNAIRE(SUBJECT,STEMNUM,TEAID,CREATETIME)
VALUES('我的测试','2','T130401',NOW());

SELECT * FROM log WHERE usrName='B13040333' 
AND TIME<'2011-11-02 12:00' AND TIME>'2017-02-02 12:00'



/*删表*/
DROP TABLE USR;
DROP TABLE Student;
DROP TABLE TEACHER;
DROP TABLE QUESTIONNAIRE;
DROP TABLE SELECTQUESTION;
DROP TABLE QUESTION;
DROP TABLE MYOPTION;
DROP TABLE ANSWER;
DROP TABLE SYMBOL;
DROP TABLE Survey;
DROP TABLE collectAnswer;
DROP TABLE MYRESTRICT;
DROP TABLE LOG;


/*删数据*/
DELETE FROM TEACHER; 
DELETE FROM MYOPTION; 
DELETE FROM ANSWER;
DELETE FROM SURVEY;  
DELETE FROM student; 
DELETE FROM MYRESTRICT;  



/**/
SET FOREIGN_KEY_CHECKS = 0;
SET FOREIGN_KEY_CHECKS = 1;







/*测试*/
INSERT INTO TEACHER(teaID,teaName,teaMail,TEATELPHONEL)
VALUES('T130401','李','2256284823@qq.com','18351872345')
INSERT INTO QUESTION(WID,TID,STEM,OPTIONNUM,TYPE)
VALUES('3','3','你的建议','1','jianda')
SELECT * FROM collectAnswer WHERE (TEAID='T130401' AND WID='5') AND ACTIVITY='哈哈'
SELECT * FROM Student WHERE STUID='B13040333'
SELECT * FROM TEACHER WHERE TEAID='T130401'
SELECT * FROM ANSWER WHERE ANSWERID='哈哈';
SELECT * FROM collectAnswer WHERE TEAID='T130401' AND WID='4'
