server:
  port: 8010
spring:
  application:
    name: microservice-consumer-user
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
microservice-provider-user:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

#»´æ÷≈‰÷√
#ribbon:
#  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule