#spring:
#  application:
#    name: microservice-discovery-eureka-ava
#---
#spring:
#  profiles: peer1
#server:
#  port: 8761
#eureka:
#  instance:
#    hostname: peer1
#  client:
#    service-url:
#      #将自己注册到peer2这个Eureka上面去
#      defaultZone: http://peer2:8762/eureka
#---
#spring:
#  profiles: peer2
#server:
#  port: 8762
#eureka:
#  instance:
#    hostname: peer2
#  client:
#    service-url:
#      #将自己注册到peer1这个Eureka上面去
#      defaultZone: http://peer1:8761/eureka

#另一种配置方式
spring:
  application:
    name: microservice-discovery-eureka-ava
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka,http://peer2:8762/eureka
---
spring:
  profiles: peer1
server:
  port: 8761
eureka:
  instance:
    hostname: peer1
---
spring:
  profiles: peer2
server:
  port: 8762
eureka:
  instance:
    hostname: peer2
